### ISSUE TITLE
nsbl.ahbl.org  entfernen

### ISSUE THREAD

**Issue by Tobida** [RogerSik/dnsbl-check#7]
nsbl.ahbl.org hat seinen Dienst eingestellt. Und zwar in der Form, dass es seit dem 1.1.2015 nur noch positive Rückmeldungen gibt. Bitte einfach aus der Liste entfernen.

Infos dazu:
http://www.ahbl.org/content/last-notice-wildcarding-services-jan-1st

**Comment by RogerSik** [comment]
Hallo Tobida,

vielen Dank für deine Rückmeldung!

Habe den Dienst nun aus der Liste entfernt.

Grüße
Roger
